Create RemoveTools.lua
va1kio/commander pull request #33
Opened 2021-03-16 21:16 UTC by ccuser44

Removes the tools of the player

2021-03-16 21:31 UTC, JEK0x81D requested changes
Make sure that you're also clearing any tools that may be currently equipped by the player inside the character.

2021-03-16 21:41 UTC, ccuser44 commented
Thank you for the suggestion 😄

2021-03-16 22:27 UTC, JEK0x81D approved these changes

2021-03-16 22:47 UTC, merged

2021-03-16 22:58 UTC, JEK0x81D commented on src/ServerScriptService/Server/Packages/RemoveTools.lua
> +		if Backpack then
ps Typo here.

2021-03-17 06:55 UTC, ccuser44 commented on src/ServerScriptService/Server/Packages/RemoveTools.lua
> +		if Backpack then
Ok made a pull to fix it.